# Generated by Django 2.1.1 on 2018-09-04 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='blog',
            name='tpublish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
